name: 'tag-protector'
description: "Rejects tag that doesn't follow the rule"
author: 'KeisukeYamashita'
inputs:
  rule: 
    required: true
    description: 'Format of the tag should be'
    default: 'true'
  deleteTag:
    required: false
    description: 'Delete the tag or not'
    default: 'true'
  failWorkflow:
    required: false
    description: 'Fail the workflow if not tag match the rule'
    default: 'false'
  repository:
    required: false
    description: 'The GitHub repository containing the issue or pr.'
    default: ${{ github.repository }}
  token:
    required: false
    description: 'Credential to access to the repo to post the comment'
    default: ${{ github.token }}
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: 'stop-circle'
  color: 'red'
